# Site settings
title: Elio Blog
SEOTitle: elio 的博客 | Elio Blog
header-img: img/home-bg.jpg
email: elio_chiu@163.com
description: "A whole new world"
keyword: "elio, eliochiu, @elio, Elio Blog, 博客, 个人网站"
url: "https://eliochiu.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    eliochiu
#twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx
mail: elio_chiu@163.com



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-minifier]

jekyll-minifier:
  exclude: 'atom.xml'
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_boolean_attributes: true  # Default: false
  compress_js_templates: true      # Default: false
  uglifier_args:
    harmony: true

sitemap: true

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# utterances
utterances_comment: true
# Disqus
# disqus_username: roife-github-io

# ga_track_id: 'UA-177087620-1'            # Format: UA-xxxxxx-xx
# ga_domain: eliochiu.github.io


# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "独自寻遍地球 找新的出口"
sidebar-avatar: /img/avatar-elio-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 5              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false


# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false
page-katex: false

# Friends
friends: [
    # {
    #     title: "Matrixkook",
    #     href: "https://matrixkook.github.io"
    # }, {
    #     title: "bazoka13",
    #     href: "https://bazoka13.github.io/"
    # }, {
    #   title: "Coekjan",
    #   href: "https://coekjan.github.io/"
    # }, {
    #   title: "Thysrael",
    #   href: "https://thysrael.github.io/"
    # }
]
